name: Java CI com Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Baixa seu código na máquina virtual

      - name: Configurar JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18' # Certifique-se de que este número é 18
          distribution: 'temurin'
          cache: maven

      - name: Build e Testes com Maven
        run: mvn -B test -Dsurefire.printSummary=true

      - name: Upload do Relatório de Cobertura
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cobertura-jacoco
          path: target/site/jacoco/